namespace AiNetReview.FastTests.Catalog;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using AiNetReview.Core.Analysis;
using AiNetReview.Core.Catalog;
using AiNetReview.Core.Rules;
using AiNetReview.Core.Rules.TemplateNoOp;

public sealed class CatalogWriterTests
{
    [Fact]
    public async Task WriteAsync_CreatesDeterministicCatalogAndExampleFromRegisteredDescriptors()
    {
        using var tempDirectory = TestTempDirectory.Create();
        var configuredFilePath = tempDirectory.CreateFile("ainetreview.json", "preserve me");
        var registry = new RuleRegistry([new TemplateNoOpRule(), new ScenarioRule()]);
        var writer = new CatalogWriter(registry);

        await writer.WriteAsync(tempDirectory.DirectoryPath);
        var markdownPath = tempDirectory.GetPath(Path.Combine("docs", "ainetreview-rules.md"));
        var examplePath = tempDirectory.GetPath("ainetreview.example.json");
        var markdownBytes = await File.ReadAllBytesAsync(markdownPath);
        var exampleBytes = await File.ReadAllBytesAsync(examplePath);
        var markdown = await File.ReadAllTextAsync(markdownPath);

        await writer.WriteAsync(tempDirectory.DirectoryPath);

        Assert.Equal(markdownBytes, await File.ReadAllBytesAsync(markdownPath));
        Assert.Equal(exampleBytes, await File.ReadAllBytesAsync(examplePath));
        Assert.False(
            markdownBytes.Length >= 3 && markdownBytes[0] == 0xEF && markdownBytes[1] == 0xBB && markdownBytes[2] == 0xBF,
            "Generated Markdown should use UTF-8 without a byte-order mark.");
        Assert.EndsWith("\n", markdown, StringComparison.Ordinal);
        Assert.Contains("<!-- Generated by AiNetReview. Do not edit. -->", markdown, StringComparison.Ordinal);
        Assert.Contains("Technical template", markdown, StringComparison.Ordinal);
        Assert.True(
            markdown.IndexOf("## Scenario Rule (`scenario-rule`)", StringComparison.Ordinal) <
            markdown.IndexOf("## Template No-Op (`template-noop`)", StringComparison.Ordinal));
        Assert.Equal("preserve me", await File.ReadAllTextAsync(configuredFilePath));

        using var example = JsonDocument.Parse(exampleBytes);
        var root = example.RootElement;
        Assert.Equal(1, root.GetProperty("schemaVersion").GetInt32());
        Assert.Equal(string.Empty, root.GetProperty("solution").GetString());
        Assert.Equal("audit-reporting", root.GetProperty("outputDirectory").GetString());
        Assert.Equal(".ainetreview", root.GetProperty("storageDirectory").GetString());
        var rules = root.GetProperty("rules");
        Assert.Equal(new[] { "scenario-rule", "template-noop" }, rules.EnumerateObject().Select(static property => property.Name));
        Assert.Equal("base", rules.GetProperty("scenario-rule").GetProperty("scenario").GetString());
        Assert.Empty(rules.GetProperty("template-noop").EnumerateObject());
    }

    [Fact]
    public async Task WriteAsync_RequiresAnExistingAbsoluteProjectRoot()
    {
        using var tempDirectory = TestTempDirectory.Create();
        var writer = new CatalogWriter(new RuleRegistry([new TemplateNoOpRule()]));

        await Assert.ThrowsAsync<ArgumentException>(() => writer.WriteAsync("relative-root"));
        await Assert.ThrowsAsync<DirectoryNotFoundException>(() => writer.WriteAsync(
            Path.Combine(tempDirectory.DirectoryPath, "missing")));
    }

    private sealed class ScenarioRule : IReviewRule
    {
        public RuleDescriptor Descriptor { get; } = new(
            ruleId: "scenario-rule",
            title: "Scenario Rule",
            behaviorVersion: 1,
            purpose: "Demonstrates descriptor-backed options.",
            measurement: "The scenario value is used by this test rule.",
            reviewQuestions: ["Does the scenario match the test input?"],
            options: [RuleOptionDescriptor.String("scenario", "Scenario name", "base")]);

        public Task<RuleResult> ExecuteAsync(
            ReviewContext context,
            RuleOptions options,
            CancellationToken cancellationToken) => Task.FromResult(RuleResult.Empty);
    }
}
