namespace AiNetReview.Core.Catalog;

using System;
using System.IO;
using System.Text;
using System.Text.Json;
using System.Text.Json.Nodes;
using System.Threading;
using System.Threading.Tasks;
using AiNetReview.Core.Rules;

public sealed class CatalogWriter
{
    private const string MarkdownFileName = "ainetreview-rules.md";
    private const string ExampleFileName = "ainetreview.example.json";
    private static readonly UTF8Encoding Utf8WithoutBom = new(encoderShouldEmitUTF8Identifier: false);
    private static readonly JsonSerializerOptions JsonOptions = new() { WriteIndented = true };
    private readonly RuleRegistry registry;

    public CatalogWriter(RuleRegistry registry)
    {
        ArgumentNullException.ThrowIfNull(registry);
        this.registry = registry;
    }

    public async Task WriteAsync(string projectRoot, CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(projectRoot);
        if (!Path.IsPathFullyQualified(projectRoot))
        {
            throw new ArgumentException("Project root must be an absolute path.", nameof(projectRoot));
        }

        var fullProjectRoot = Path.GetFullPath(projectRoot);
        if (!Directory.Exists(fullProjectRoot))
        {
            throw new DirectoryNotFoundException($"Project root does not exist: {fullProjectRoot}");
        }

        var documentationDirectory = Path.Combine(fullProjectRoot, "docs");
        Directory.CreateDirectory(documentationDirectory);
        var markdownPath = Path.Combine(documentationDirectory, MarkdownFileName);
        var exampleConfigPath = Path.Combine(fullProjectRoot, ExampleFileName);

        await File.WriteAllTextAsync(
            markdownPath,
            CreateMarkdown(),
            Utf8WithoutBom,
            cancellationToken).ConfigureAwait(false);
        await File.WriteAllTextAsync(
            exampleConfigPath,
            CreateExampleConfig(),
            Utf8WithoutBom,
            cancellationToken).ConfigureAwait(false);
    }

    private string CreateMarkdown()
    {
        var content = new StringBuilder();
        AppendLine(content, "# AiNetReview Rule Catalog");
        AppendLine(content);
        AppendLine(content, "<!-- Generated by AiNetReview. Do not edit. -->");

        foreach (var rule in registry.Rules)
        {
            var descriptor = rule.Descriptor;
            AppendLine(content);
            AppendLine(content, $"## {NormalizeLines(descriptor.Title)} (`{NormalizeLines(descriptor.RuleId)}`)");
            AppendLine(content);
            if (descriptor.IsTemplate)
            {
                AppendLine(content, "> Technical template; this rule does not assess code quality.");
                AppendLine(content);
            }

            AppendLine(content, $"- Behavior version: {descriptor.BehaviorVersion}");
            AppendLine(content);
            AppendLine(content, "### Purpose");
            AppendLine(content);
            AppendLine(content, NormalizeLines(descriptor.Purpose));
            AppendLine(content);
            AppendLine(content, "### Measurement");
            AppendLine(content);
            AppendLine(content, NormalizeLines(descriptor.Measurement));
            AppendLine(content);
            AppendLine(content, "### Review questions");
            AppendLine(content);
            foreach (var question in descriptor.ReviewQuestions)
            {
                AppendLine(content, $"- {NormalizeLines(question)}");
            }

            AppendLine(content);
            AppendLine(content, "### Options");
            AppendLine(content);
            if (descriptor.Options.Count == 0)
            {
                AppendLine(content, "This rule has no options.");
            }
            else
            {
                foreach (var option in descriptor.Options)
                {
                    var defaultJson = JsonSerializer.Serialize(option.DefaultValue);
                    AppendLine(content, $"- `{NormalizeLines(option.Name)}` (default `{defaultJson}`): {NormalizeLines(option.Description)}");
                }
            }
        }

        return content.ToString();
    }

    private string CreateExampleConfig()
    {
        var rules = new JsonObject();
        foreach (var rule in registry.Rules)
        {
            var options = new JsonObject();
            foreach (var option in rule.Descriptor.ResolveOptions().Values)
            {
                options.Add(option.Key, JsonNode.Parse(option.Value.GetRawText()));
            }

            rules.Add(rule.Descriptor.RuleId, options);
        }

        var configuration = new JsonObject
        {
            ["schemaVersion"] = JsonValue.Create(1),
            ["solution"] = JsonValue.Create(string.Empty),
            ["outputDirectory"] = JsonValue.Create("audit-reporting"),
            ["storageDirectory"] = JsonValue.Create(".ainetreview"),
            ["rules"] = rules,
        };

        return JsonSerializer.Serialize(configuration, JsonOptions) + "\n";
    }

    private static void AppendLine(StringBuilder content, string value = "") =>
        content.Append(value).Append('\n');

    private static string NormalizeLines(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal).Replace('\r', '\n');
}
