namespace AiNetReview.Core.Analysis;

using System;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

/// <summary>Classifies source and project scope for product review analyses.</summary>
internal static class ReviewSourceClassifier
{
    private static readonly string[] TestReferenceAssemblyPrefixes =
    [
        "xunit",
        "nunit",
        "mstest",
        "microsoft.testplatform",
        "microsoft.visualstudio.testplatform",
        "microsoft.visualstudio.testtools.unittesting",
        "microsoft.testing",
    ];

    private static readonly string[] TestProjectSuffixes =
    [
        "Tests",
        "Test",
        "UnitTests",
        "UnitTest",
        "IntegrationTests",
        "IntegrationTest",
        "FastTests",
        "ComponentTests",
        "TestKit",
        "Specs",
        "Spec",
    ];

    private static readonly string[] TestPathSegments =
    [
        "test",
        "tests",
        "unittests",
        "integrationtests",
        "fasttests",
        "componenttests",
        "testkit",
        "spec",
        "specs",
    ];

    public static ProjectClassificationResult ClassifyProject(Project project)
    {
        ArgumentNullException.ThrowIfNull(project);

        if (project.MetadataReferences.Any(static reference => IsTestReferenceAssembly(reference.Display)))
        {
            return new ProjectClassificationResult(ProjectRole.Tests, ProjectClassificationReason.TestReferenceAssembly);
        }

        if (HasTestProjectSuffix(project.Name))
        {
            return new ProjectClassificationResult(ProjectRole.Tests, ProjectClassificationReason.ProjectNameSuffix);
        }

        if (!string.IsNullOrWhiteSpace(project.FilePath))
        {
            var normalizedPath = NormalizeSeparators(project.FilePath);
            if (HasTestProjectSuffix(Path.GetFileNameWithoutExtension(normalizedPath)))
            {
                return new ProjectClassificationResult(ProjectRole.Tests, ProjectClassificationReason.ProjectFileNameSuffix);
            }

            if (normalizedPath.Split('/', StringSplitOptions.RemoveEmptyEntries)
                .Any(static segment => TestPathSegments.Contains(segment, StringComparer.OrdinalIgnoreCase)))
            {
                return new ProjectClassificationResult(ProjectRole.Tests, ProjectClassificationReason.ProjectPathSegment);
            }
        }

        return new ProjectClassificationResult(ProjectRole.Production, ProjectClassificationReason.NoTestMarker);
    }

    public static bool IsTestProject(Project project) => ClassifyProject(project).Role == ProjectRole.Tests;

    public static async Task<bool> IsGeneratedDocumentAsync(Document document, CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(document);
        cancellationToken.ThrowIfCancellationRequested();

        var path = document.FilePath ?? document.Name;
        if (IsGeneratedPath(path))
        {
            return true;
        }

        var sourceText = await document.GetTextAsync(cancellationToken).ConfigureAwait(false);
        return HasAutoGeneratedHeader(sourceText);
    }

    public static bool IsGeneratedSymbol(ISymbol symbol)
    {
        ArgumentNullException.ThrowIfNull(symbol);

        for (ISymbol? current = symbol; current is not null; current = current.ContainingType)
        {
            foreach (var attribute in current.GetAttributes())
            {
                if (attribute.AttributeClass?.ToDisplayString() is
                    "System.CodeDom.Compiler.GeneratedCodeAttribute"
                    or "System.Runtime.CompilerServices.CompilerGeneratedAttribute")
                {
                    return true;
                }
            }
        }

        return false;
    }

    internal static bool IsTestReferenceAssembly(string? display)
    {
        if (string.IsNullOrWhiteSpace(display))
        {
            return false;
        }

        var assemblyName = Path.GetFileNameWithoutExtension(display);
        return TestReferenceAssemblyPrefixes.Any(prefix => assemblyName.StartsWith(prefix, StringComparison.OrdinalIgnoreCase));
    }

    private static bool HasTestProjectSuffix(string value)
    {
        foreach (var suffix in TestProjectSuffixes)
        {
            if (!value.EndsWith(suffix, StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            var suffixStart = value.Length - suffix.Length;
            if (suffixStart == 0
                || value[suffixStart - 1] == '.'
                || char.IsUpper(value[suffixStart]))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsGeneratedPath(string path)
    {
        var normalized = NormalizeSeparators(path);
        var fileName = Path.GetFileName(normalized);
        return normalized.Contains("/obj/", StringComparison.OrdinalIgnoreCase)
            || normalized.StartsWith("obj/", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".g.i.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || fileName.EndsWith(".designer.cs", StringComparison.OrdinalIgnoreCase);
    }

    private static bool HasAutoGeneratedHeader(SourceText sourceText)
    {
        var lineCount = Math.Min(5, sourceText.Lines.Count);
        for (var index = 0; index < lineCount; index++)
        {
            if (sourceText.Lines[index].ToString().Contains("<auto-generated", StringComparison.OrdinalIgnoreCase))
            {
                return true;
            }
        }

        return false;
    }

    private static string NormalizeSeparators(string path) => path.Replace('\\', '/');
}
