namespace AiNetReview.FastTests.Analysis;

using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading;
using AiNetReview.Core.Analysis;
using AiNetReview.Core.Findings;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

public sealed class ReviewSourceClassifierTests
{
    [Fact]
    public void IsTestProject_RecognizesKnownReferencesNamesAndPaths()
    {
        using var workspace = new AdhocWorkspace();
        var root = Path.Combine(Path.GetTempPath(), "AiNetReview-Classification");
        var byName = AddProject(workspace, "Example.FastTests", Path.Combine(root, "src", "Example.FastTests.csproj"));
        var byPath = AddProject(workspace, "Example", Path.Combine(root, "tests", "Example", "Example.csproj"));
        var byReference = AddProject(
            workspace,
            "Example",
            Path.Combine(root, "src", "Example.csproj"),
            [MetadataReference.CreateFromFile(typeof(FactAttribute).Assembly.Location)]);

        Assert.True(ReviewSourceClassifier.IsTestProject(byName));
        Assert.True(ReviewSourceClassifier.IsTestProject(byPath));
        Assert.True(ReviewSourceClassifier.IsTestProject(byReference));
    }

    [Fact]
    public void IsTestProject_DoesNotClassifyOrdinaryNamesOrLookalikePaths()
    {
        using var workspace = new AdhocWorkspace();
        var root = Path.Combine(Path.GetTempPath(), "AiNetReview-Classification");
        var project = AddProject(workspace, "Contest", Path.Combine(root, "src", "Contest.csproj"));

        Assert.False(ReviewSourceClassifier.IsTestProject(project));
    }

    [Theory]
    [InlineData("C:/repo/obj/Generated.cs", true)]
    [InlineData("src/Feature.g.cs", true)]
    [InlineData("src/Feature.g.i.cs", true)]
    [InlineData("src/Feature.generated.cs", true)]
    [InlineData("src/Feature.designer.cs", true)]
    [InlineData("src/Feature.GENERATED.CS", true)]
    [InlineData("src/Feature.cs", false)]
    public async Task IsGeneratedDocumentAsync_RecognizesPathMarkers(string path, bool expected)
    {
        using var fixture = CreateDocument(path, "public class Feature {}");

        var isGenerated = await ReviewSourceClassifier.IsGeneratedDocumentAsync(fixture.Document, CancellationToken.None);

        Assert.Equal(expected, isGenerated);
    }

    [Fact]
    public async Task IsGeneratedDocumentAsync_RecognizesHeaderWithinFirstFiveLinesOnly()
    {
        using var firstFive = CreateDocument(
            "src/Header.cs",
            "// generated by fixture\n/* source */\n\n// <auto-generated />\npublic class Generated {}");
        using var sixth = CreateDocument(
            "src/SixthLine.cs",
            "// one\n// two\n// three\n// four\n// five\n// <auto-generated />\npublic class NotDetected {}");
        using var ordinary = CreateDocument("src/Ordinary.cs", "// ordinary\npublic class Ordinary {}");

        Assert.True(await ReviewSourceClassifier.IsGeneratedDocumentAsync(firstFive.Document, CancellationToken.None));
        Assert.False(await ReviewSourceClassifier.IsGeneratedDocumentAsync(sixth.Document, CancellationToken.None));
        Assert.False(await ReviewSourceClassifier.IsGeneratedDocumentAsync(ordinary.Document, CancellationToken.None));
    }

    [Fact]
    public void IsGeneratedMethod_RecognizesMethodAndContainingTypeAttributes()
    {
        const string source = """
            using System.CodeDom.Compiler;
            using System.Runtime.CompilerServices;
            [GeneratedCode("generator", "1")]
            public class GeneratedByType { public void Run() {} }
            [CompilerGenerated]
            public class CompilerGeneratedType { public void Run() {} }
            public class Ordinary
            {
                [GeneratedCode("generator", "1")] public void GeneratedMethod() {}
                [CompilerGenerated] public void CompilerGeneratedMethod() {}
                public void Run() {}
            }
            """;
        var tree = CSharpSyntaxTree.ParseText(source);
        var compilation = CSharpCompilation.Create(
            "ReviewSourceClassifierTests",
            [tree],
            PlatformReferences(),
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
        var semanticModel = compilation.GetSemanticModel(tree);
        var methods = tree.GetRoot().DescendantNodes().OfType<MethodDeclarationSyntax>()
            .ToDictionary(
                method => method.Ancestors().OfType<TypeDeclarationSyntax>().First().Identifier.ValueText + "." + method.Identifier.ValueText,
                method => (IMethodSymbol)semanticModel.GetDeclaredSymbol(method)!,
                StringComparer.Ordinal);

        Assert.True(ReviewSourceClassifier.IsGeneratedSymbol(methods["GeneratedByType.Run"]));
        Assert.True(ReviewSourceClassifier.IsGeneratedSymbol(methods["CompilerGeneratedType.Run"]));
        Assert.True(ReviewSourceClassifier.IsGeneratedSymbol(methods["Ordinary.GeneratedMethod"]));
        Assert.True(ReviewSourceClassifier.IsGeneratedSymbol(methods["Ordinary.CompilerGeneratedMethod"]));
        Assert.False(ReviewSourceClassifier.IsGeneratedSymbol(methods["Ordinary.Run"]));
    }

    [Fact]
    public void GetProjectRelativePath_NormalizesAndRejectsPathsOutsideTheReviewRoot()
    {
        using var workspace = new AdhocWorkspace();
        using var root = TestTempDirectory.Create();
        var context = new ReviewContext(workspace.CurrentSolution, root.DirectoryPath);

        Assert.Equal("src/Feature.cs", context.GetProjectRelativePath(Path.Combine(root.DirectoryPath, "src", "Feature.cs")));
        var exception = Assert.Throws<AnalysisFailedException>(() => context.GetProjectRelativePath(Path.Combine(root.DirectoryPath, "..", "Outside.cs")));
        Assert.Contains("outside the project root", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task CurrentFindingValidator_PreservesOutsideRootAnalysisFailure()
    {
        using var workspace = new AdhocWorkspace();
        using var root = TestTempDirectory.Create();
        var projectId = ProjectId.CreateNewId();
        workspace.AddProject(ProjectInfo.Create(
            projectId,
            VersionStamp.Create(),
            "Example",
            "Example",
            LanguageNames.CSharp,
            filePath: Path.Combine(root.DirectoryPath, "src", "Example.csproj")));
        workspace.AddDocument(DocumentInfo.Create(
            DocumentId.CreateNewId(projectId),
            "Outside.cs",
            filePath: Path.Combine(root.DirectoryPath, "..", "Outside.cs"),
            loader: TextLoader.From(TextAndVersion.Create(SourceText.From("class Outside {}"), VersionStamp.Create()))));
        var context = new ReviewContext(workspace.CurrentSolution, root.DirectoryPath);

        var exception = await Assert.ThrowsAsync<AnalysisFailedException>(() => new CurrentFindingValidator()
            .ValidateAndSortAsync("example-rule", context, Array.Empty<FindingDraft>()));

        Assert.Contains("outside the project root", exception.Message, StringComparison.OrdinalIgnoreCase);
    }

    private static Project AddProject(
        AdhocWorkspace workspace,
        string name,
        string filePath,
        IEnumerable<MetadataReference>? metadataReferences = null)
    {
        var projectId = ProjectId.CreateNewId();
        workspace.AddProject(ProjectInfo.Create(
            projectId,
            VersionStamp.Create(),
            name,
            name,
            LanguageNames.CSharp,
            filePath: filePath,
            compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary),
            metadataReferences: metadataReferences));
        return workspace.CurrentSolution.GetProject(projectId)!;
    }

    private static DocumentFixture CreateDocument(string path, string source)
    {
        var workspace = new AdhocWorkspace();
        var projectId = ProjectId.CreateNewId();
        var directory = Path.GetDirectoryName(path) ?? "src";
        workspace.AddProject(ProjectInfo.Create(
            projectId,
            VersionStamp.Create(),
            "Example",
            "Example",
            LanguageNames.CSharp,
            filePath: Path.Combine(Path.GetTempPath(), "AiNetReview", "Example.csproj"),
            compilationOptions: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary)));
        var documentId = DocumentId.CreateNewId(projectId);
        workspace.AddDocument(DocumentInfo.Create(
            documentId,
            Path.GetFileName(path),
            filePath: path,
            folders: directory.Split([Path.DirectorySeparatorChar, Path.AltDirectorySeparatorChar, '/'], StringSplitOptions.RemoveEmptyEntries),
            loader: TextLoader.From(TextAndVersion.Create(SourceText.From(source), VersionStamp.Create()))));
        return new DocumentFixture(workspace, workspace.CurrentSolution.GetDocument(documentId)!);
    }

    private static IEnumerable<MetadataReference> PlatformReferences() =>
        ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))!
        .Split(Path.PathSeparator, StringSplitOptions.RemoveEmptyEntries)
        .Select(static assemblyPath => MetadataReference.CreateFromFile(assemblyPath));

    private sealed class DocumentFixture(AdhocWorkspace workspace, Document document) : IDisposable
    {
        public Document Document { get; } = document;

        public void Dispose() => workspace.Dispose();
    }
}
