namespace AiNetReview.Core.Rules.MethodControlFlowOutliers;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Threading;
using System.Threading.Tasks;
using AiNetReview.Core.Analysis;
using AiNetReview.Core.Findings;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

/// <summary>Reports methods with unusually high decision counts or decision nesting within their project.</summary>
public sealed class MethodControlFlowOutliersRule : IReviewRule
{
    private const int DefaultPercentile = 90;
    private static readonly RuleOptionDescriptor PercentileOption = new(
        name: "percentile",
        description: "Nearest-rank percentile used independently for decision count and maximum nesting (integer 50 through 99).",
        defaultValue: JsonSerializer.SerializeToElement(DefaultPercentile),
        validator: static value => value.ValueKind == JsonValueKind.Number
            && value.TryGetInt32(out var percentile)
            && percentile is >= 50 and <= 99);

    public RuleDescriptor Descriptor { get; } = new(
        ruleId: "method-control-flow-outliers",
        title: "Method Control-Flow Outliers",
        behaviorVersion: 1,
        purpose: "Flags methods with unusually many decisions or deeply nested decision paths in their project.",
        measurement: "decisionCount counts each if, switch section (including default; grouped labels count as one section), switch-expression arm, conditional expression, loop, and catch clause. decisionConstructCount counts each if, conditional expression, loop, and catch once, but counts each whole switch statement/expression once. maxDecisionNesting is the deepest nesting of counted decisions; each switch section/arm forms a decision level, while else-if chains stay at the same level. sourceSpanLines is the inclusive line span of the method declaration and is context only. groupMethodCount is the project's eligible executable method count. Only method declarations with a body or expression body are compared. Local functions and lambdas are excluded from their containing method. Test projects are skipped when identified by known test-framework assembly names, common project-name/file suffixes, or exact test-path segments. Generated documents are skipped for /obj/ paths, .g.cs/.g.i.cs/.generated.cs/.designer.cs names, or an <auto-generated marker in the first five source lines. Methods and containing types marked GeneratedCode or CompilerGenerated are skipped. Per-project thresholds use the configured nearest-rank percentile (ceil(percentile * method count), one-based), with minimum cutoffs of 8 decisions and 4 nested decisions. A method is reported when (decisionCount meets its cutoff and decisionConstructCount is at least 2) or maxDecisionNesting meets its cutoff; ties are included. decisionRank and nestingRank are descending competition ranks; equal values share the same rank.",
        reviewQuestions:
        [
            "Can a reader follow the decisions and loops in this method without repeatedly reconstructing earlier conditions?",
            "Do the nested paths express one cohesive operation, and are there important interactions a reviewer should verify?",
        ],
        options: [PercentileOption]);

    public async Task<RuleResult> ExecuteAsync(
        ReviewContext context,
        RuleOptions options,
        CancellationToken cancellationToken)
    {
        ArgumentNullException.ThrowIfNull(context);
        ArgumentNullException.ThrowIfNull(options);
        cancellationToken.ThrowIfCancellationRequested();

        var percentile = options["percentile"].GetInt32();
        var projects = context.Solution.Projects
            .Where(static project => project.Language == LanguageNames.CSharp)
            .OrderBy(static project => project.FilePath, StringComparer.Ordinal)
            .ThenBy(static project => project.Name, StringComparer.Ordinal);
        var findings = new List<FindingDraft>();

        foreach (var project in projects)
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (ReviewSourceClassifier.IsTestProject(project))
            {
                continue;
            }

            var projectMethods = await AnalyzeProjectAsync(context, project, cancellationToken).ConfigureAwait(false);
            if (projectMethods.Count == 0)
            {
                continue;
            }

            var decisionPercentileValue = NearestRank(projectMethods.Select(static method => method.DecisionCount), percentile);
            var nestingPercentileValue = NearestRank(projectMethods.Select(static method => method.MaxDecisionNesting), percentile);
            var decisionCutoff = Math.Max(8, decisionPercentileValue);
            var nestingCutoff = Math.Max(4, nestingPercentileValue);
            var groupCount = projectMethods.Count;

            foreach (var method in projectMethods
                         .OrderBy(static method => method.SourcePath, StringComparer.Ordinal)
                         .ThenBy(static method => method.StartLine)
                         .ThenBy(static method => method.SubjectId, StringComparer.Ordinal))
            {
                cancellationToken.ThrowIfCancellationRequested();
                var countPathSelected = method.DecisionCount >= decisionCutoff && method.DecisionConstructCount >= 2;
                var nestingPathSelected = method.MaxDecisionNesting >= nestingCutoff;
                if (!countPathSelected && !nestingPathSelected)
                {
                    continue;
                }

                var decisionRank = 1 + projectMethods.Count(candidate => candidate.DecisionCount > method.DecisionCount);
                var nestingRank = 1 + projectMethods.Count(candidate => candidate.MaxDecisionNesting > method.MaxDecisionNesting);
                findings.Add(CreateFinding(
                    method,
                    groupCount,
                    percentile,
                    decisionPercentileValue,
                    nestingPercentileValue,
                    decisionCutoff,
                    nestingCutoff,
                    countPathSelected,
                    nestingPathSelected,
                    decisionRank,
                    nestingRank));
            }
        }

        return new RuleResult(findings);
    }

    private static async Task<List<MethodMeasurement>> AnalyzeProjectAsync(
        ReviewContext context,
        Project project,
        CancellationToken cancellationToken)
    {
        var measurements = new List<MethodMeasurement>();
        foreach (var document in project.Documents.OrderBy(static item => item.FilePath, StringComparer.Ordinal))
        {
            cancellationToken.ThrowIfCancellationRequested();
            if (string.IsNullOrWhiteSpace(document.FilePath)
                || !document.FilePath.EndsWith(".cs", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            if (await ReviewSourceClassifier.IsGeneratedDocumentAsync(document, cancellationToken).ConfigureAwait(false))
            {
                continue;
            }

            var root = await document.GetSyntaxRootAsync(cancellationToken).ConfigureAwait(false);
            var sourceText = await document.GetTextAsync(cancellationToken).ConfigureAwait(false);
            var semanticModel = await document.GetSemanticModelAsync(cancellationToken).ConfigureAwait(false);
            if (root is null || semanticModel is null || string.IsNullOrWhiteSpace(document.FilePath))
            {
                continue;
            }

            foreach (var declaration in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
            {
                cancellationToken.ThrowIfCancellationRequested();
                if (declaration.Body is null && declaration.ExpressionBody is null)
                {
                    continue;
                }

                var symbol = semanticModel.GetDeclaredSymbol(declaration, cancellationToken);
                if (symbol is null || ReviewSourceClassifier.IsGeneratedSymbol(symbol))
                {
                    continue;
                }

                var body = (SyntaxNode?)declaration.Body ?? declaration.ExpressionBody!.Expression;
                var visitor = new DecisionVisitor();
                visitor.Visit(body);

                var sourcePath = context.GetProjectRelativePath(document.FilePath);
                var projectPath = context.GetProjectRelativePath(project.FilePath!);
                var declarationLines = sourceText.Lines.GetLinePositionSpan(declaration.Span);
                var subjectId = DocumentationCommentId.CreateDeclarationId(symbol)
                    ?? symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                var evidence = GetEvidence(sourceText, declaration.Identifier);

                measurements.Add(new MethodMeasurement(
                    sourcePath,
                    projectPath,
                    subjectId,
                    declarationLines.Start.Line + 1,
                    declarationLines.End.Line + 1,
                    visitor.DecisionCount,
                    visitor.DecisionConstructCount,
                    visitor.MaxDecisionNesting,
                    evidence,
                    visitor.DeepestDecision is { } deepestDecision
                        ? GetEvidence(sourceText, GetDecisionEvidenceToken(deepestDecision))
                        : null));
            }
        }

        return measurements;
    }

    private static int NearestRank(IEnumerable<int> values, int percentile)
    {
        var sorted = values.Order().ToArray();
        var rank = (int)Math.Ceiling(percentile / 100d * sorted.Length);
        return sorted[rank - 1];
    }

    private static SourceEvidence GetEvidence(SourceText sourceText, SyntaxToken token)
    {
        var lineIndex = sourceText.Lines.GetLineFromPosition(token.SpanStart).LineNumber;
        var line = sourceText.Lines[lineIndex];
        var lineText = line.ToString();
        if (lineText.Length <= 180)
        {
            return new SourceEvidence(lineIndex + 1, lineText.Trim());
        }

        const int maximumSnippetLength = 180;
        var tokenStart = token.SpanStart - line.Start;
        var tokenEnd = token.Span.End - line.Start;
        var tokenLength = tokenEnd - tokenStart;
        var snippetStart = Math.Max(0, tokenStart - Math.Max(0, (maximumSnippetLength - tokenLength) / 2));
        snippetStart = Math.Min(snippetStart, lineText.Length - maximumSnippetLength);
        if (snippetStart > tokenStart)
        {
            snippetStart = tokenStart;
        }

        var snippetEnd = Math.Min(lineText.Length, Math.Max(snippetStart + maximumSnippetLength, tokenEnd));
        if (snippetEnd - snippetStart > maximumSnippetLength)
        {
            snippetStart = snippetEnd - maximumSnippetLength;
        }

        var snippet = lineText[snippetStart..snippetEnd].Trim();
        return new SourceEvidence(lineIndex + 1, snippet);
    }

    private static SyntaxToken GetDecisionEvidenceToken(SyntaxNode node) => node switch
    {
        IfStatementSyntax statement => statement.IfKeyword,
        SwitchSectionSyntax section => section.Labels[0].GetFirstToken(),
        SwitchExpressionArmSyntax arm => arm.EqualsGreaterThanToken,
        ConditionalExpressionSyntax conditional => conditional.QuestionToken,
        ForStatementSyntax statement => statement.ForKeyword,
        ForEachStatementSyntax statement => statement.ForEachKeyword,
        ForEachVariableStatementSyntax statement => statement.ForEachKeyword,
        WhileStatementSyntax statement => statement.WhileKeyword,
        DoStatementSyntax statement => statement.DoKeyword,
        CatchClauseSyntax clause => clause.CatchKeyword,
        _ => node.GetFirstToken(),
    };

    private static FindingDraft CreateFinding(
        MethodMeasurement method,
        int groupCount,
        int percentile,
        int decisionPercentileValue,
        int nestingPercentileValue,
        int decisionCutoff,
        int nestingCutoff,
        bool countPathSelected,
        bool nestingPathSelected,
        int decisionRank,
        int nestingRank)
    {
        var rationale = countPathSelected
            ? $"Included because decisionCount {method.DecisionCount} meets cutoff {decisionCutoff} across {method.DecisionConstructCount} separate decision constructs (minimum 2)."
            : $"Included because maxDecisionNesting {method.MaxDecisionNesting} meets cutoff {nestingCutoff}.";
        if (countPathSelected && nestingPathSelected)
        {
            rationale += $" It also meets the nesting cutoff {nestingCutoff} at depth {method.MaxDecisionNesting}.";
        }

        rationale += $" The project group has {groupCount} eligible methods; nearest-rank P{percentile} values are {decisionPercentileValue} decisions and {nestingPercentileValue} nested decisions. Ties are included. Review question: are the conditions and paths easy to follow, and do branch interactions need closer review?";
        var evidence = new List<FindingEvidence>
        {
            new(method.SourcePath, method.Evidence.Line, "Method declaration", "Measured executable method declaration.", method.Evidence.Snippet),
        };
        if (method.DeepestDecisionEvidence is { } decisionEvidence)
        {
            evidence.Add(new FindingEvidence(
                method.SourcePath,
                decisionEvidence.Line,
                "Deepest counted decision",
                "This source token identifies a decision construct included in the method's measurements.",
                decisionEvidence.Snippet));
        }

        return new FindingDraft(
            method.ProjectPath,
            method.SourcePath,
            method.SubjectId,
            "control-flow-outlier",
            method.StartLine,
            rationale,
            new Dictionary<string, double>(StringComparer.Ordinal)
            {
                ["decisionCount"] = method.DecisionCount,
                ["decisionConstructCount"] = method.DecisionConstructCount,
                ["maxDecisionNesting"] = method.MaxDecisionNesting,
                ["sourceSpanLines"] = method.EndLine - method.StartLine + 1,
                ["groupMethodCount"] = groupCount,
                ["percentile"] = percentile,
                ["decisionPercentileValue"] = decisionPercentileValue,
                ["nestingPercentileValue"] = nestingPercentileValue,
                ["decisionCutoff"] = decisionCutoff,
                ["nestingCutoff"] = nestingCutoff,
                ["decisionRank"] = decisionRank,
                ["nestingRank"] = nestingRank,
            },
            evidence);
    }

    private sealed record SourceEvidence(int Line, string Snippet);

    private sealed record MethodMeasurement(
        string SourcePath,
        string ProjectPath,
        string SubjectId,
        int StartLine,
        int EndLine,
        int DecisionCount,
        int DecisionConstructCount,
        int MaxDecisionNesting,
        SourceEvidence Evidence,
        SourceEvidence? DeepestDecisionEvidence);

    private sealed class DecisionVisitor : CSharpSyntaxWalker
    {
        private int decisionDepth;

        public int DecisionCount { get; private set; }

        public int DecisionConstructCount { get; private set; }

        public int MaxDecisionNesting { get; private set; }

        public SyntaxNode? DeepestDecision { get; private set; }

        public override void VisitIfStatement(IfStatementSyntax node)
        {
            var baseDepth = decisionDepth;
            CountDecisionConstruct(baseDepth + 1, node);
            VisitAtDepth(node.Condition, baseDepth + 1);
            VisitAtDepth(node.Statement, baseDepth + 1);
            if (node.Else is { } elseClause)
            {
                if (elseClause.Statement is IfStatementSyntax elseIf)
                {
                    VisitIfAtDepth(elseIf, baseDepth);
                }
                else
                {
                    VisitAtDepth(elseClause.Statement, baseDepth + 1);
                }
            }
        }

        public override void VisitSwitchStatement(SwitchStatementSyntax node)
        {
            var baseDepth = decisionDepth;
            DecisionConstructCount++;
            VisitAtDepth(node.Expression, baseDepth);
            foreach (var section in node.Sections)
            {
                CountDecision(baseDepth + 1, section);
                foreach (var label in section.Labels)
                {
                    VisitAtDepth(label, baseDepth + 1);
                }

                foreach (var statement in section.Statements)
                {
                    VisitAtDepth(statement, baseDepth + 1);
                }
            }
        }

        public override void VisitSwitchExpression(SwitchExpressionSyntax node)
        {
            var baseDepth = decisionDepth;
            DecisionConstructCount++;
            VisitAtDepth(node.GoverningExpression, baseDepth);
            foreach (var arm in node.Arms)
            {
                CountDecision(baseDepth + 1, arm);
                VisitAtDepth(arm, baseDepth + 1);
            }
        }

        public override void VisitConditionalExpression(ConditionalExpressionSyntax node) => VisitDecisionNode(node);

        public override void VisitForStatement(ForStatementSyntax node) => VisitDecisionNode(node);

        public override void VisitForEachStatement(ForEachStatementSyntax node) => VisitDecisionNode(node);

        public override void VisitForEachVariableStatement(ForEachVariableStatementSyntax node) => VisitDecisionNode(node);

        public override void VisitWhileStatement(WhileStatementSyntax node) => VisitDecisionNode(node);

        public override void VisitDoStatement(DoStatementSyntax node) => VisitDecisionNode(node);

        public override void VisitCatchClause(CatchClauseSyntax node) => VisitDecisionNode(node);

        public override void VisitLocalFunctionStatement(LocalFunctionStatementSyntax node)
        {
        }

        public override void VisitSimpleLambdaExpression(SimpleLambdaExpressionSyntax node)
        {
        }

        public override void VisitParenthesizedLambdaExpression(ParenthesizedLambdaExpressionSyntax node)
        {
        }

        public override void VisitAnonymousMethodExpression(AnonymousMethodExpressionSyntax node)
        {
        }

        public override void VisitClassDeclaration(ClassDeclarationSyntax node)
        {
        }

        public override void VisitStructDeclaration(StructDeclarationSyntax node)
        {
        }

        public override void VisitRecordDeclaration(RecordDeclarationSyntax node)
        {
        }

        public override void VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
        {
        }

        private void VisitIfAtDepth(IfStatementSyntax node, int baseDepth)
        {
            var savedDepth = decisionDepth;
            decisionDepth = baseDepth;
            VisitIfStatement(node);
            decisionDepth = savedDepth;
        }

        private void VisitDecisionNode(SyntaxNode node)
        {
            var baseDepth = decisionDepth;
            CountDecisionConstruct(baseDepth + 1, node);
            VisitChildrenAtDepth(node, baseDepth + 1);
        }

        private void VisitAtDepth(SyntaxNode node, int depth)
        {
            var savedDepth = decisionDepth;
            decisionDepth = depth;
            Visit(node);
            decisionDepth = savedDepth;
        }

        private void VisitChildrenAtDepth(SyntaxNode node, int depth)
        {
            var savedDepth = decisionDepth;
            decisionDepth = depth;
            foreach (var child in node.ChildNodes())
            {
                Visit(child);
            }

            decisionDepth = savedDepth;
        }

        private void CountDecisionConstruct(int depth, SyntaxNode node)
        {
            DecisionConstructCount++;
            CountDecision(depth, node);
        }

        private void CountDecision(int depth, SyntaxNode node)
        {
            DecisionCount++;
            if (depth > MaxDecisionNesting)
            {
                MaxDecisionNesting = depth;
                DeepestDecision = node;
            }
        }
    }
}
